"""Add coins and checkins tables

Revision ID: 3c9fb42692be
Revises: 4442cf1684dc
Create Date: 2025-11-22 13:47:26.422202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c9fb42692be'
down_revision: Union[str, Sequence[str], None] = '4442cf1684dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('office', sa.String(), nullable=False),
    sa.Column('coins_earned', sa.Integer(), nullable=False),
    sa.Column('is_first_of_week', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_table('coins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coins_id'), 'coins', ['id'], unique=False)
    op.alter_column('users', 'office',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'interests',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('users', 'grade',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'company_start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'grade',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'interests',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('users', 'office',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_coins_id'), table_name='coins')
    op.drop_table('coins')
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_table('checkins')
    # ### end Alembic commands ###
